### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by a-mellor** [fazibear/airbrakex#30]
Our Airbrake notification errors have been working correctly until recently when we started getting SSL certification errors:

```
iex(1)> Airbrakex.notify RuntimeError.exception("hi")
[error] SSL: :certify: ssl_handshake.erl:1605:Fatal error: bad certificate

{:error, %HTTPoison.Error{id: nil, reason: {:tls_alert, 'bad certificate'}}}
```

```
config :airbrakex,
  environment: to_string(Mix.env()),
  project_key: Env.get("AIRBRAKE_API_KEY"),
  project_id: Env.get("AIRBRAKE_PROJECT_ID"),
  endpoint: "https://airbrake.io"
```

Does it look like we have the configuration wrong?

**Comment by lpil** [comment]
Seems airbrake's SSL cert is invalid

https://www.ssllabs.com/ssltest/analyze.html?d=airbrake.io&s=52.4.152.44

**Comment by a-mellor** [comment]
Thanks.

**Comment by lpil** [comment]
Possibly re-open? This library is currently broken because of airbrake @a-mellor

**Comment by lpil** [comment]
I've emailed their support about this.

**Comment by lpil** [comment]
Their support have fixed this.
