### ISSUE TITLE
outdated package in hexpm

### ISSUE THREAD

**Issue by silva96** [fazibear/airbrakex#43]
Current version in master is 0.1.7 and in [hex.pm](https://hex.pm/packages/airbrakex) it is 0.1.6 , what's the reason of this?

**Comment by aturkewi** [comment]
I would like to second this as well. I had added a PR back in September: https://github.com/fazibear/airbrakex/pull/39 that still does not appear to be in master. 

I would also suggest adding releases in Github so it's easy to find the source code for the version that I am currently working with :)

**Comment by fazibear** [comment]
Yeah! Sorry about that, I've merged things and forgot to release!

**Comment by fazibear** [comment]
⚡️
